### ISSUE TITLE
no notifications in slack channel

### ISSUE THREAD

**Issue by rushins** [bitnami-labs/kubewatch#213] opened 2020-04-11 19:40 UTC
Hi 

i setup the kubewatch as per the setup from this github  and everything working , but i dont see any notifications in my slack chanell 

the POD running and configmap with the slack channel and slack token is all configured ?
any logs to check ? 

i see this error checking the logs of the pod
-------
logging before flag.Parse: E0411 13:47:34.574859       1 reflector.go:205] github.com/bitnami-labs/kubewatch/pkg/controller/controller.go:377: Failed to list *v1beta1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:slack-int:kubewatch" cannot list resource "deployments" in API group "apps" at the cluster scope

any idea . 
BR,

**Comment by mickael-ange** [comment] 2020-05-26 06:21
Looks like you have an ServiceAccount or RBAC issue.

**Comment by mkmik** [comment] 2020-07-02 21:37
duplicate of #200

fixed but not released yet

**Comment by rushins** [comment] 2020-07-02 21:51
> Looks like you have an ServiceAccount or RBAC issue.

yes, RBAC is mandate on all K8S right ? so what is the fix 
@mkmik : when you say fixed it ? what does it mean

**Comment by mkmik** [comment] 2020-07-02 21:56
sorry I fat-fingered this

**Comment by mkmik** [comment] 2020-07-02 21:57
Duplicate of #149

**Comment by mkmik** [comment] 2020-07-02 21:57
it _seems_ the same problem as in #149

**Closed by mkmik** 2020-07-02 21:57 UTC
